### ISSUE TITLE
Resnet18 Pre-synthesis failed.

### ISSUE THREAD

**Issue by kanhao100** [UIUC-ChenLab/ScaleHLS-HIDA#12]
I ran HIDA according to the Readme file and got a new resnet18.cpp file instead of the one included in the repository, and the synthesis using Vitis HLS also failed.

```
INFO: [HLS 200-111] Finished Checking Synthesizability: CPU user time: 0 seconds. CPU system time: 0 seconds. Elapsed time: 0.736 seconds; current allocated memory: 1.394 GB.
ERROR: [HLS 200-997] Found unsupported dataflow constructs in function 'forward_node166' (resnet18_0324.cpp:4414): the loop (resnet18_0324.cpp:4419:22) has multiple exit points.

ERROR: [HLS 200-997] Found unsupported dataflow constructs in function 'forward_node161' (resnet18_0324.cpp:4247): the loop (resnet18_0324.cpp:4251:22) has multiple exit points.

INFO: [XFORM 203-721] Changing loop 'VITIS_LOOP_66_1' (resnet18_0324.cpp:67)  to a process function for dataflow in function 'forward_node0'.
INFO: [XFORM 203-721] Changing loop 'VITIS_LOOP_3583_1' (resnet18_0324.cpp:3584)  to a process function for dataflow in function 'forward_node140'.
ERROR: [HLS 200-994] Cannot read value of  'v1932' from previous iterations in dataflow VITIS_LOOP_3777_1  (resnet18_0324.cpp:3780)  of function 'forward_node140'.
ERROR: [HLS 200-1715] Encountered problem during source synthesis
ERROR: [HLS 200-70] Pre-synthesis failed.
INFO: [HLS 200-111] Finished Command csynth_design CPU user time: 4 seconds. CPU system time: 0 seconds. Elapsed time: 39.677 seconds; current allocated memory: 0.000 MB.
command 'ap_source' returned error code
    while executing
"source E:/0Project/ResNet18_FPGA_Design/HIDA_0324/HIDA_0324/solution1/csynth.tcl"
    invoked from within
"hls::main E:/0Project/ResNet18_FPGA_Design/HIDA_0324/HIDA_0324/solution1/csynth.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel 1 hls::main {*}$newargs"
    (procedure "hls_proc" line 16)
    invoked from within
"hls_proc [info nameofexecutable] $argv"
INFO: [HLS 200-112] Total CPU user time: 5 seconds. Total CPU system time: 0 seconds. Total elapsed time: 41.386 seconds; peak allocated memory: 1.394 GB.
Finished C synthesis.
```

**Comment by hanchenye** [comment]
This is a Vitis HLS bug that has been fixed in their latest release. Please try 2024.1/2024.2.

**Comment by kanhao100** [comment]
> This is a Vitis HLS bug that has been fixed in their latest release. Please try 2024.1/2024.2.这是 Vitis HLS 的一个错误，已在最新版本中修复。请尝试 2​​024.1/2024.2。

Hi, I already tried it on Vitis v2024.2, but it's still the same. Could you suggest any other ideas?

```
 INFO: [XFORM 203-721] Changing loop 'VITIS_LOOP_4848_1' (../HIDA_0324/resnet18_0324.cpp:4848)  to a process function for dataflow in function 'forward_node140'.
[ERROR] ERROR: [HLS 200-994] Cannot read value of  'v3141' from previous iterations in dataflow VITIS_LOOP_5175_1  (../HIDA_0324/resnet18_0324.cpp:5175)  of function 'forward_node140'.
[ERROR] ERROR: [HLS 200-1715] Encountered problem during source synthesis
[ERROR] ERROR: [HLS 200-70] Pre-synthesis failed.
 ERROR: 
 INFO: [HLS 200-112] Total CPU user time: 25 seconds. Total CPU system time: 2 seconds. Total elapsed time: 146.259 seconds; peak allocated memory: 290.777 MB.
[ERROR] Failed to run synthesis
```

**Comment by hanchenye** [comment]
The "multiple exit points" issue has been fixed :)

The new issue you mentioned is due to a fully partitioned array. For example, if array A[8] is partitioned with a factor of 8, then Vitis treats it as 8 scalars instead of an array. Scalars cannot be used for the communication between two dataflow tasks in Vitis. This is another bug in Vitis...

If this happens, I'd suggest you to set "unroll_factor" smaller and/or "tiling_factor" larger, which will typically fix the issue.

A hacky but more robust way is: if an array is fully partitioned, increase the size of one dimension of the array by 1. For example, change A[8] to A[9]. Nothing else needs to be touched. If you want, you can implement this small hack in the C++ emitter with a few lines of code.

**Comment by kanhao100** [comment]
> The "multiple exit points" issue has been fixed :)
> 
> The new issue you mentioned is due to a fully partitioned array. For example, if array A[8] is partitioned with a factor of 8, then Vitis treats it as 8 scalars instead of an array. Scalars cannot be used for the communication between two dataflow tasks in Vitis. This is another bug in Vitis...
> 
> If this happens, I'd suggest you to set "unroll_factor" smaller and/or "tiling_factor" larger, which will typically fix the issue.
> 
> A hacky but more robust way is: if an array is fully partitioned, increase the size of one dimension of the array by 1. For example, change A[8] to A[9]. Nothing else needs to be touched. If you want, you can implement this small hack in the C++ emitter with a few lines of code.

Yes, no more "multiple exit points" issue.
But I tried very larger loop-tile-size and set loop-unroll-factor=0, but it doesn't work :(
Could you tell me what other parameter I should adjust? How can I limit the number of BRAMs and DSPs?

**Comment by dsandall** [comment]
Hi kanhao - were you ever able to solve your issue? I am encountering very similar errors when synthesizing scalehls output code

**Comment by kanhao100** [comment]
> Hi kanhao - were you ever able to solve your issue? I am encountering very similar errors when synthesizing scalehls output code

Unfortunately, I'm afraid I was never able to solve it. I just gave up on it. Sorry I couldn't be of more help. If you find a solution, please let me know.
